### PR TITLE
porting to 8.6. Warning: an Admitted in Deadcodeproof.

### PR DESCRIPTION
**Pull request by MarisaKirisame**
Hello, I am trying to port compcert to 8.6. 
I need some help here, as I have a admit in backend/Deadcodeproof.v that I cant get rid off... 
Also, I havent test whether it work or not on 8.5 (but I'm pretty sure it dont, because some tactic are now 'stronger' and automatically do more, like backend/Unusedglobproof.v, and some name changes), so what could be done to keep the compatibility?

### CODE REVIEW

**Comment by MarisaKirisame** [comment]
also intro x; do_something x break in cparser/Parser.v, but it seems to be generated... can anyone hand me a pointer to how vy work?

**Comment by xavierleroy** [comment]
Concerning the problem with Coq 8.6 and the Menhir-generated file Parser.v, the expert is @jhjourdan and I hope he'll be able to look into that at some future point.

Concerning compatibility in general, every major version of Coq breaks CompCert, so we don't even try to support multiple versions of Coq: every release of CompCert is pinned to one version of Coq.  

So, some future release of CompCert will be for Coq 8.6, but I don't know which one yet and at what time we will make the switch to 8.6, since it is often necessary to wait for a pl1 or pl2 bug-fix release of Coq.

**Comment by jhjourdan** [comment]
Indeed, I'll have a look at that. What is the priority?

**Comment by MarisaKirisame** [comment]
The menhir problem lies not in compcert but in menhir source code...
https://github.com/npm-ml/menhir/blob/19e70f27c4bb3b99a01d8cdff6e301bde74d4fba/src/coqBackend.ml
at line 247 and 412 the line 
fprintf f "Local Obligation Tactic := intro x; case x; reflexivity.\n\n";
break in 8.6. 
simply changing it to
fprintf f "Local Obligation Tactic := let x := fresh in intro x; case x; reflexivity.\n\n";
seems to be able to fix the problem. I will make a pull request to menhir soon...

**Comment by jhjourdan** [comment]
Nice, thank you for the patch. It should be compatible with 8.6.

I will patch menhir soon and @fpottier should be able to do a release.

**Comment by jhjourdan** [comment]
I did that on menhir. It worked. If you need that, I guess  @fpottier can do a release soon.

Btw, there are still quite a few errors/warnings shown by Coq.

**Comment by MarisaKirisame** [comment]
@jhjourdan most of the warnings are Implicit Arguments being deprecated; I will fix that soon.
However I cannot discharge the admit in deadcode... Also what other errors do you got?

**Comment by MarisaKirisame** [comment]
The latest commit remove some of the warning

**Comment by xavierleroy** [comment]
Thanks for your contribution, it's great to have others exploring new Coq versions :-)  See also pull request #156 for a complementary effort.  I'm discussing with the other parties involved to decide when to switch CompCert to Coq 8.6.

**Comment by xavierleroy** [comment]
The switch to Coq 8.6 is complete, both in git master and in the latest release 3.0.1.  Thanks for all your input.

**Comment by MarisaKirisame** [comment]
👍

**Pull request closed without merging**
