### PR TITLE
Adapt w.r.t. coq/coq#19343.

### PR DESCRIPTION
**Pull request by ppedrot**
Should be backwards compatible.

### CODE REVIEW

**Comment by xavierleroy** [comment]
Thanks for the patch.  It seems to be about extraction, while https://github.com/coq/coq/pull/19343 is about functional induction.  Could you tell us more?

**Comment by proux01** [comment]
coq/coq#19343 removes the dependency of stdlib's MSetAVL on FunInd which is itself requiring Extraction.
It appears Compcert was relying on this transitive requirement, the current pull request just makes that requirement explicit.

**Comment by xavierleroy** [comment]
Crystal clear!  Thanks for the explanation.

**Comment by xavierleroy** [comment]
I think that in the long run Menhir itself should generate the `Require Extraction` directive.  https://gitlab.inria.fr/fpottier/menhir/-/issues/75

**Pull request merged**
