### PR TITLE
Upgrade embedded version of Flocq to 3.1, continued

### PR DESCRIPTION
**Pull request by xavierleroy**
This is a follow-up to pull request #273.  The only difference is that there are fewer changes to Makefile, because we keep the old approach of using `-R` for the `flocq` directory, instead of using `-Q`.

### CODE REVIEW

**Comment by xavierleroy** [comment]
For their information: @silene @bschommer @m-schmidt .

**Comment by silene** [comment]
I am fine with `-R`. My reason for `-Q` was to detect potential conflicts. Indeed, module names from Flocq 3 have become quite bland, e.g., `Binary`, so I wanted to make extra sure I was not introducing any conflict.

By the way, changes to the `.gitignore` file are no longer needed.

**Comment by xavierleroy** [comment]
Thanks for the quick reply.  I agree with the blandness of the module names :-) and the need for `-Q` in the future.  Will fix the .gitignore too.

**Comment by bschommer** [comment]
The changes work fine in our build and testing infrastructure, thanks for the work on this.

Just a minor note, it seems to be the case that ````.nra.cache```` is missing in the ````.gitignore````.

**Comment by xavierleroy** [comment]
Thanks @bschommer for the re-test and the hint about `.gitignore`.  There are a lot of cache files that Coq can generate :-).  Merging now...

**Pull request merged**
